# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: deploy data

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "devtools"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Test
        run: devtools::test(cran = FALSE)
        shell: Rscript {0}
      - name: Deploy local
        uses: s0/git-publish-subdir-action@v2.4.0
        env: 
          REPO: self
          BRANCH: distro
          FOLDER: to_distro
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 

